sudo: required
dist: trusty
language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - rm -rf $HOME/miniconda_dlfa && bash miniconda.sh -b -p $HOME/miniconda_dlfa
  - export PATH="$HOME/miniconda_dlfa/bin:$PATH"
before_script:
  - pip install -r requirements.txt
script:
  - sbt clean test
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
