# use new container-based travis workers
sudo: false
dist: trusty

language: python

cache:
  directories:
  - /home/travis/download
  - /home/travis/miniconda
  - /home/travis/.cache/pip

env:
  matrix:
    # test tensorflow keras backend
    - KERAS_BACKEND="tensorflow"
    # test theano keras backend
    - KERAS_BACKEND="theano"
    # pylint checks skip the tests
    - RUN_PYLINT="true" SKIP_TESTS="true"

install: source build_tools/travis/install.sh
script: bash build_tools/travis/test_script.sh